image: archlinux
packages:
  - hut
  - mise

oauth: pages.sr.ht/PAGES:RW
environment:
  site: railpacked.farthergate.com
  repo: railpacked

tasks:
  - build: |
      cd $repo
      mise i
      mise run build
  - package: |
      cd $repo/_build
      tar -cvz . > ../../../site.tar.gz
  - upload: |
      hut pages publish -d $site site.tar.gz
